- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - check-requirements
    check:
      jobs:
        - openstack-tox-pep8:
            voting: false
        - openstack-tox-py27:
            voting: false
        - openstack-tox-py35:
            voting: false
        - openstack-tox-cover:
            voting: false
    gate:
      jobs:
        - openstack-tox-pep8:
            voting: false
        - openstack-tox-py27:
            voting: false
        - openstack-tox-py35:
            voting: false
        - openstack-tox-cover:
            voting: false
