- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - check-requirements
    check:
      jobs:
        - monasca-tempest-python-mysql:
            voting: false
        - monasca-tempest-python-postgresql:
            voting: false
        - monasca-tempest-java-mysql:
            voting: false
        - monasca-tempest-java-postgresql:
            voting: false
        - openstack-tox-cover
    gate:
      jobs:
        - openstack-tox-cover
